version: "2"

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000" # UI.
      - "8000:8000" 

volumes:
  portainer_data:
