name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          key: ${{ secrets.DEPLOY_SSH_SECRET }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          script: |
            bash /deploy-compose.sh
